const dtcClassName = {
    commonAddItem: "dtc-common-add-item",
    commonChevronUp: "dtc-common-chevron-up",
    commonChevron: "dtc-common-chevron",
    commonCleanList: "dtc-common-clean-list",
    commonControlRegion: "dtc-common-control-region",
    commonControlSingleLineWrapper: "dtc-common-control-single-line-wrapper",
    commonControl: "dtc-common-control",
    commonDefaultFont: "dtc-common-default-font",
    commonEllipsis: "dtc-common-ellipsis",
    commonFormControlDisabled: "dtc-common-form-control-disabled",
    commonFormControlIndicator: "dtc-common-form-control-indicator",
    commonInputBackplate: "dtc-common-input-backplate",
    commonInput: "dtc-common-input",
    commonInteractiveFormControlIndicator:
        "dtc-common-interactive-form-control-indicator",
    commonInvalidMessage: "dtc-common-invalid-message",
    commonLabelRegion: "dtc-common-label-region",
    commonLabel: "dtc-common-label",
    commonRemoveItem: "dtc-common-remove-item",
    commonRequired: "dtc-common-required",
    commonSelectInput: "dtc-common-select-input",
    commonSelectSpan: "dtc-common-select-span",
    commonSoftRemoveInput: "dtc-common-soft-remove-input",
    commonSoftRemove: "dtc-common-soft-remove",
    controlButton: "dtc-control-button",
    controlButton__disabled: "dtc-control-button__disabled",
    controlTextField: "dtc-control-text-field",
    controlTextField__disabled: "dtc-control-text-field__disabled",
    controlToggle: "dtc-control-toggle",
} as const;

export default dtcClassName;
