name: Validate

on:
  push:
    branches: 
      - main
      - gh-pages
      - 'features/**'
  pull_request:
    branches: 
      - main
      - gh-pages
      - 'features/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16.x]
    
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Cache multiple paths
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Install Dependencies
      run: npm ci

    - name: Build package files
      run: npm run build --workspace=design-to-code --workspace=design-to-code-react

    - name: Build test app
      run: npm run build:app --workspace=design-to-code --workspace=design-to-code-react

    - name: Install playwright browsers
      run: npx playwright install

    - name: Test design to code package
      run: npm run test --workspace=design-to-code
    
    - name: Create test report for design to code package
      run: npm run test:report --workspace=design-to-code

    - name: Publish design to code package report
    - uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        lcov-file: ./packages/design-to-code/coverage/lcov.info

    - name: Test design to code react package
      run: npm run test --workspace=design-to-code-react

    - name: Create test report for design to code package
      run: npm run test:report --workspace=design-to-code-react

    - name: Publish design to code react package report
    - uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        lcov-file: ./packages/design-to-code-react/coverage/lcov.info

    - name: Build docs site
      run: npm run build:gh-pages

       